### ISSUE TITLE
`vignette/plots.qmd` breaks on -SD, Mean, SD because of wrong types

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/pymarginaleffects#110]

**Comment by vincentarelbundock** [comment]
@artiom-matvei can you check the `plot_*()` functions for `threenum`, which should have labels: "-SD", "Mean", and "SD" in the legend of the plot.

**Comment by artiom-matvei** [comment]
It is supposed to be fixed with the last PR (see the images below coming from the PR tests): 
https://github.com/vincentarelbundock/pymarginaleffects/pull/120
![plot-slopes](https://github.com/artiom-matvei/pymarginaleffects/blob/c25f6509c69cee4797d1931f1f7fa6d0bd83dabd/tests/images/plot_slopes/issue_114_06.png?raw=true)
![plot-predictions](https://github.com/artiom-matvei/pymarginaleffects/blob/c25f6509c69cee4797d1931f1f7fa6d0bd83dabd/tests/images/plot_predictions/issue_114_04.png?raw=true)

**Comment by vincentarelbundock** [comment]
Fantastic
