### ISSUE TITLE
Bug for `pyfixest` methods with no fixed effects + some basic tests against fixest

### ISSUE THREAD

**Issue by s3alfisc** [vincentarelbundock/pymarginaleffects#78]
Hi @vincentarelbundock , there is a small bug in the handling of `self._fixef`. The attribute is always returned and `None` if the model has no fixed effects. In consequence, `pymarginaleffects` throws an error when no fixed effects are specified in `feols()`. I'll open a PR with a quick fix in a few minutes!

**Comment by s3alfisc** [comment]
Btw, I am also happy to get rid of the tests and open another PR for them - just let me know what you prefer! =)

**Comment by vincentarelbundock** [comment]
Oh no worries about PR structure. I'm just super happy you're willing to spend some time on this. I just appreciate anything you can put together!

Looks like there's an issue with `pyfixest` not being installed in CI github action. I probably won't have time to look at that specific problem for a while, but otherwise the PR looks fantastic and I'd hit "merge" as soon as I see a green CI light.

**Comment by s3alfisc** [comment]
Hi @vincentarelbundock, tests currently fail because pyfixest depends on numba, which currently does not seem to work with Python 3.12. I'll have to think of a workaround later today!

**Comment by s3alfisc** [comment]
CI tests work now: `pyfixest` is only a dev dependency on python versions `<3.12` and `pyfixest` specific tests only run if `pyfixest` is installed.
